{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "fox_deneb",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "fox_deneb",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fox_deneb_db",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "fox_deneb_db",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fox_stellar_core",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "measurement": "fox_stellar_core",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fox_stellar_core_db",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "measurement": "fox_stellar_core_db",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fox_horizon",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "fox_horizon",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fox_horizon_db",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "measurement": "fox_horizon_db",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fox_stellar_core_horizon",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "measurement": "fox_stellar_core_horizon",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}