version: '3'
services:
  cygnus:
    container_name: fox_cygnus
    image: cygnus:latest
    ports:
      - 8082:3000
    volumes:
      - ${SENSITIVE_CONFIG_ROOT}/cygnus.js:/cygnus/src/config.js
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  deneb:
    container_name: fox_deneb
    image: deneb:latest
    volumes:
      - ${SENSITIVE_CONFIG_ROOT}/deneb.json:/deneb/src/config/configuration.json
    links:
      - deneb-db
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  deneb-db:
    container_name: fox_deneb_db
    image: deneb-db:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=deneb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=aquila
    volumes:
      - ${DATA_ROOT}/deneb-db:/var/lib/postgresql/data:z
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

#  stellar-core-horizon:
#    container_name: fox_stellar_core_horizon
#    image: stellar/quickstart:v10-stable
#    ports:
#      - 5433:5432
#      - 8000:8000
#    volumes:
#    # - /etc/passwd:/etc/passwd:ro
#      - ${DATA_ROOT}/stellar-core-horizon:/opt/stellar"
#    # user: "${USER_ME}:${GROUP_ME}"
#    command:
#      - --testnet
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "tcp://127.0.0.1:24224"
#        tag: "{{.Name}}"
#    depends_on:
#      - fluentd

  horizon:
    container_name: fox_horizon
    image: stellarfox/horizon:ubuntu-18.04-v0.14.2 
    restart: always
    command:
      - horizon
      - --ingest=true
      - --db-url=dbname=horizon user=horizon password=horizon host=fox_horizon_db port=5432 sslmode=disable
      - --stellar-core-db-url=host=stellar-core-db port=5432 user=core password=core sslmode=disable
      - --stellar-core-url=host=fox_stellar_core port=11626 sslmode=disable
    ports:
      - 8001:8000
    links:
      - horizon-db
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  horizon-db:
    container_name: fox_horizon_db
    image: postgres:11.0-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_USER=horizon
    volumes:
      - ${DATA_ROOT}/horizon-db:/var/lib/postgresql/data:z
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  stellar-core:
    container_name: fox_stellar_core
    image: stellarfox/stellar-core:alpine-3.8-v10.0.0 
    ports:
      - 11626:11626
    volumes:
      - ${SENSITIVE_CONFIG_ROOT}/stellar-core.cfg:/etc/stellar-core.cfg:ro
      - ${DATA_ROOT}/stellar-core-history:/tmp/stellar-core/history/vs:z
    command:
      - stellar-core
      - --conf
      - /etc/stellar-core.cfg
    links:
      - stellar-core-db
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  stellar-core-db:
    container_name: fox_stellar_core_db
    hostname: fox_stellar_core_db
    image: postgres:11.0-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_USER=core
    volumes:
      - ${DATA_ROOT}/stellar-core-db:/var/lib/postgresql/data:z
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  pgadmin:
    container_name: fox_pgadmin
    image: dpage/pgadmin4:3.5
    ports:
      - 8084:80
    volumes:
      - ${DATA_ROOT}/pgadmin:/var/lib/pgadmin
      - ${LOG_ROOT}/pgadmin:/var/log/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=password
    links:
      - deneb-db
#      - stellar-core-horizon
      - horizon-db
      - stellar-core-db

  influxdb:
    container_name: fox_influxdb
    image: influxdb:1.5.4-alpine
    ports:
      - 8086:8086
      - 8089:8089
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${CONFIG_ROOT}/influxdb:/etc/influxdb:ro
      - ${DATA_ROOT}/influxdb:/var/lib/influxdb
    user: "${USER_ME}:${GROUP_ME}"
    command: "influxd -config /etc/influxdb/influxdb.conf"

  chronograf:
    container_name: fox_chronograf
    image: chronograf:1.5.0-alpine
    ports:
      - 8888:8888
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${DATA_ROOT}/chronograf:/var/lib/chronograf
    user: "${USER_ME}:${GROUP_ME}"
    command: "chronograf --influxdb-url=http://fox_influxdb:8086 --kapacitor-url=http://fox_kapacitor:9092"
    links:
      - influxdb
      - kapacitor

  telegraf:
    container_name: fox_telegraf
    image: telegraf:1.6.4-alpine
    volumes:
      - ${CONFIG_ROOT}/telegraf:/etc/telegraf:ro
      - /var/run:/var/run:ro
    links:
      - influxdb
  
  kapacitor:
    container_name: fox_kapacitor
    image: kapacitor:1.5.1-alpine
    ports:
      - 9092:9092
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${CONFIG_ROOT}/kapacitor:/etc/kapacitor:ro
      - ${DATA_ROOT}/kapacitor:/var/lib/kapacitor
    user: "${USER_ME}:${GROUP_ME}"
    links:
      - influxdb
  
  grafana:
    container_name: fox_grafana
    image: grafana/grafana:5.3.2 
    environment:
      - FORCE_HOSTNAME=fox_grafana
      - INFLUXDB_HOST=fox_influxdb
      - GRAFANA_USER=admin
      - GRAFANA_PASS=admin
    ports:
      - 8081:3000
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${DATA_ROOT}/grafana:/var/lib/grafana
    user: "${USER_ME}:${GROUP_ME}"
    links:
      - influxdb

  dns:
    container_name: fox_dns
    image: defreitas/dns-proxy-server
    ports:
      - 5380:5380
      - 53:53
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  nginx:
    container_name: fox_nginx
    hostname: .${DOMAIN}
    environment:
      - HOSTNAMES="grafana.${DOMAIN},pgadmin.${DOMAIN},chronograf.${DOMAIN},cygnus.${DOMAIN},${DOMAIN}"
    image: nginx:1.15.5-alpine
    ports:
      - 80:80
    volumes:
      - ${CONFIG_ROOT}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONFIG_ROOT}/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${LOG_ROOT}/nginx:/var/log/nginx
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://127.0.0.1:24224"
        tag: "{{.Name}}"
    depends_on:
      - fluentd
      - pgadmin
      - chronograf
      - cygnus
      - grafana

  fluentd:
    container_name: fox_fluentd
    image: edoproject/fluentd-collector:latest
    network_mode: host
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${CONFIG_ROOT}/fluentd:/fluentd/etc:ro
      - ${LOG_ROOT}/fluentd:/var/log
    depends_on:
      - influxdb

