version: '3'
services:
  openvpn:
    image: kylemanna/openvpn:2.4
    container_name: edo_vpn
    environment:
      - DEBUG=1
    ports:
      - 1195:1194/udp
    volumes:
      - ${DATA_ROOT}/openvpn:/etc/openvpn
    cap_add:
      - NET_ADMIN

  pgadmin:
    container_name: fox_pgadmin
    image: dpage/pgadmin4:3.5
    ports:
      - 8084:80
    volumes:
      - ${DATA_ROOT}/pgadmin:/var/lib/pgadmin
      - ${LOG_ROOT}/pgadmin:/var/log/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=password
#    links:
#      - deneb-db
#      - federation-db
#      - horizon-db
#      - stellar-core-db

  influxdb:
    container_name: fox_influxdb
    image: influxdb:1.5.4-alpine
    ports:
      - 8086:8086
      - 8089:8089
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${CONFIG_ROOT}/influxdb:/etc/influxdb:ro
      - ${DATA_ROOT}/influxdb:/var/lib/influxdb
    user: "${USER_ME}:${GROUP_ME}"
    command: "influxd -config /etc/influxdb/influxdb.conf"

  chronograf:
    container_name: fox_chronograf
    image: chronograf:1.5.0-alpine
    ports:
      - 8888:8888
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${DATA_ROOT}/chronograf:/var/lib/chronograf
    user: "${USER_ME}:${GROUP_ME}"
    command: "chronograf --influxdb-url=http://fox_influxdb:8086 --kapacitor-url=http://fox_kapacitor:9092"
    links:
      - influxdb
      - kapacitor

  telegraf:
    container_name: fox_telegraf
    image: telegraf:1.6.4-alpine
    volumes:
      - ${CONFIG_ROOT}/telegraf:/etc/telegraf:ro
      - /var/run:/var/run:ro
    links:
      - influxdb
  
  kapacitor:
    container_name: fox_kapacitor
    image: kapacitor:1.5.1-alpine
    ports:
      - 9092:9092
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${CONFIG_ROOT}/kapacitor:/etc/kapacitor:ro
      - ${DATA_ROOT}/kapacitor:/var/lib/kapacitor
    user: "${USER_ME}:${GROUP_ME}"
    links:
      - influxdb
  
  grafana:
    container_name: fox_grafana
    image: grafana/grafana:5.3.2
    environment:
      - FORCE_HOSTNAME=fox_grafana
      - INFLUXDB_HOST=fox_influxdb
      - GRAFANA_USER=admin
      - GRAFANA_PASS=admin
    ports:
      - 8081:3000
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${DATA_ROOT}/grafana:/var/lib/grafana
    user: "${USER_ME}:${GROUP_ME}"
    links:
      - influxdb

  dns:
    container_name: fox_dns
    image: defreitas/dns-proxy-server
    ports:
      - 5380:5380
      - 53:53
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf

  nginx:
    container_name: fox_nginx
    hostname: .${DOMAIN}
    environment:
      - HOSTNAMES="grafana.${DOMAIN},pgadmin.${DOMAIN},chronograf.${DOMAIN},cygnus.${DOMAIN},${DOMAIN},shambhala-client.${DOMAIN},shambhala-server.${DOMAIN}"
    image: nginx:1.15.5-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${CONFIG_ROOT}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONFIG_ROOT}/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${SENSITIVE_CONFIG_ROOT}/cert:/etc/nginx/cert:ro
      - ${LOG_ROOT}/nginx:/var/log/nginx
      - ${DATA_ROOT}/nginx:/data/www
    links:
      - pgadmin
      - chronograf 
#      - cygnus
      - grafana
      - shambhala-client
      - shambhala-server

  fluentd:
    container_name: fox_fluentd
    image: edoproject/fluentd-collector:latest
    network_mode: host
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${CONFIG_ROOT}/fluentd:/fluentd/etc:ro
      - ${LOG_ROOT}/fluentd:/var/log
    depends_on:
      - influxdb
